######### NORMAL OPERATION  ###########

### Read all films
GET http://localhost:3000/films

### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films


### Read films identified by 2
GET {{baseUrl}}/films/2

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
  "title": "L'Énigme du Temps",
  "director": "Sophie Laurent",
  "duration": -20,
  "budget": 60,
  "description": "Un voyage à travers les époques pour résoudre un mystère ancien.",
  "imageUrl": "https://example.com/image4.jpg"
}


